### ISSUE TITLE
Password with % break wrench

### ISSUE THREAD

**Issue by valdelley** [liip/wrench#13]
When I set a password with `%` in config.ini I get: 

`configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%XXXXXXSECRETXXXXXXX'`

My password in the config.ini looks like `XXXXXXXX%XXXXXXSECRETXXXXXXX`

Might be a workaround: https://github.com/flakshack/pyPerfmon/issues/1#issuecomment-73771277 but sounds like a bug to me

**Comment by sephii** [comment]
Thanks for reporting this issue. I think using `interpolation=None` in the [ConfigParser](https://docs.python.org/3.5/library/configparser.html#configparser.ConfigParser) constructor should do the trick.
