### ISSUE TITLE
import_resources results in CSRF token mismatch

### ISSUE THREAD

**Issue by gj-aazoo** [liip/wrench#17]
Running import_resources with a tabbed CSV results in CSRF token mismatch page:

gert-jan@thufir ~> wrench import_resources ./ww.txt 
If you would like to share the resources after import, enter e-mail addresses or group names below, separated by commas. Auto completion through Tab key is supported.
Recipients: NOC
Got non-ok response from server (status code 403). Contents: <!DOCTYPE html>
<html class="passbolt no-js no-passboltplugin version" lang="en">
<head>
    <meta charset="utf-8"/>
    <title>Passbolt | CSRF token mismatch.</title>
    
    <meta name="description" content="Open source password manager for teams">
    <meta name="keywords" content="Passbolt, password manager, online password manager, open source password manager">
    <meta name="robots" content="noindex, nofollow">
    <meta name="viewport" content="width=device-width">
    <link rel="shortcut icon" type="image/png" href="https://pwd.aazoo.nl/favicon.ico"/>
    <base href="https://pwd.aazoo.nl/">
    <link rel="stylesheet" href="https://pwd.aazoo.nl/css/themes/default/api_main.min.css?v=2.5.0"/></head>
<body>
<div id="container" class="error page error-404">

<header>
    <div class="header first ">
        <nav>
            <div class="top navigation primary">
                <ul>
                    <li class="left"><a href="/"><span>home</span></a></li>
                    <li class="right"><a href="/auth/login"><span>login</span></a></li>
                </ul>
            </div>
        </nav>
    </div>
</header>
<div id="content">
<div class="grid">
    <div class="row">
        <h2>CSRF token mismatch.</h2>
        <p class="error">
            The requested address was not found on this server.            Please double check the url.            Maybe the page was deleted or moved.        </p>
    </div>
</div>
</div>
<footer>
    <div class="footer">
        <ul class="footer-links">
            <li><a href="https://www.passbolt.com/terms" title="terms of service">Terms</a></li>
            <li><a href="https://www.passbolt.com/credits">Credits</a></li>
            <li id="version">
                <a href="https://www.passbolt.com/credits" class="tooltip-left" data-tooltip="2.5.0">
                    <i class="fa fa-heart-o"></i>
                    <span class="visuallyhidden">Versions</span>
                </a>
            </li>
        </ul>
    </div>
</footer>
</div>
</body>
</html>
. Sent data: {'api-version': 'v2'}
Traceback (most recent call last):
  File "/usr/local/bin/wrench", line 11, in <module>
    load_entry_point('passbolt-wrench==0.1.0', 'console_scripts', 'wrench')()
  File "/usr/local/lib/python3.6/dist-packages/passbolt_wrench-0.1.0-py3.6.egg/wrench/commands.py", line 387, in main
  File "/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/passbolt_wrench-0.1.0-py3.6.egg/wrench/commands.py", line 363, in import_resources
  File "/usr/local/lib/python3.6/dist-packages/passbolt_wrench-0.1.0-py3.6.egg/wrench/resources.py", line 100, in add_resource
  File "/usr/local/lib/python3.6/dist-packages/passbolt_wrench-0.1.0-py3.6.egg/wrench/services.py", line 35, in add_resource
  File "/usr/local/lib/python3.6/dist-packages/passbolt_wrench-0.1.0-py3.6.egg/wrench/passbolt_api.py", line 111, in add_resource
  File "/usr/local/lib/python3.6/dist-packages/passbolt_wrench-0.1.0-py3.6.egg/wrench/passbolt_api.py", line 45, in get_passbolt_response
wrench.exceptions.HttpRequestError: <Response [403]>

**Comment by sephii** [comment]
Thanks for reporting. Can you please test with the latest wrench version (0.3.0)? If that still doesn't work, please share your Passbolt version (2.2 added CSRF protection, and wrench versions before 0.2.0 are not expected to work against this version of Passbolt).

**Comment by gj-aazoo** [comment]
Hi Silvain,

Now it works, thanks for the quick fix. ☺

--
Met vriendelijke groet,

Gert-Jan de Boer
tel. +31 (0)6 151 97 449 | e-mail gert-jan@aazoo.nl<mailto:gert-jan@aazoo.nl>

[cid:49d008efeac5363518b667ad6e3e8e86183476a6.camel@aazoo.nl]<https://aazoo.nl>
________________________________
aaZoo B.V. - tel. 088 1262 400 - info@aazoo.nl<mailto:info@aazoo.nl>
Bezoek ook eens onze website op www.aazoo.nl<http://www.aazoo.nl/>

Postadres - Postbus 1017 - 8300BA Emmeloord
Bezoekadres – Ecopark 15 - 8305BJ Emmeloord
KvK 32164267 - BTW NL8217.07.899 - Rabobank NL15 RABO 0153 7186 92

Op al onze leveringen en diensten zijn onze algemene voorwaarden van toepassing zoals gedeponeerd bij de Kamer van Koophandel te Lelystad.

On Fri, 2018-12-21 at 03:02 -0800, Sylvain Fankhauser wrote:

Thanks for reporting. Can you please test with the wrench version I just released (0.2.0)? If that still doesn't work, please share your Passbolt version (2.2 added CSRF protection, and wrench versions before 0.2.0 are not expected to work against this version of Passbolt).

**Comment by sephii** [comment]
:tada:
